import { Material, Video, Bonus, Offer } from './types';

export const MATERIALS: Material[] = [
  {
    id: '1',
    title: '200 Receitas de Lanchinhos Saudáveis',
    description: 'O guia definitivo para nunca mais repetir o lanche.',
    url: 'https://drive.google.com/file/d/1L8405nV-1SYDxIF3xO1Qy4PnonuOXjDN/view?usp=sharing',
    icon: 'BookOpen',
  },
  {
    id: '2',
    title: 'Guia com Combinações de Lancheiras Prontas',
    description: 'Monte lancheiras equilibradas em menos de 5 minutos.',
    url: 'https://drive.google.com/file/d/1XEE_Dc7rRhOJrecNTDLccOL69AywnTjZ/view?usp=drive_link',
    icon: 'Layout',
  },
  {
    id: '3',
    title: 'Guia Café da Manhã Rápido',
    description: 'Comece o dia com energia e praticidade.',
    url: 'https://drive.google.com/file/d/1pr0PM13A7QmBwPGet_q4OXnoyCZ8GXwb/view?usp=drive_link',
    icon: 'Coffee',
  },
];

export const VIDEOS: Video[] = [
  // Grupo 1
  {
    id: 'v1',
    title: 'Lanches saudáveis para facilitar sua rotina',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/7k8QszIe3gc/mqdefault.jpg',
    youtubeId: '7k8QszIe3gc',
  },
  {
    id: 'v2',
    title: 'Cookie SEM TRIGO, LEITE e OVO',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/tmq2DkmLfnQ/mqdefault.jpg',
    youtubeId: 'tmq2DkmLfnQ',
  },
  {
    id: 'v3',
    title: '4 receitas incríveis com BERINJELA!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/FUmXh8nTiDU/mqdefault.jpg',
    youtubeId: 'FUmXh8nTiDU',
  },
  {
    id: 'v4',
    title: 'LEGUMES ASSADOS de dar água na boca!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/eY12pdcf3Fw/mqdefault.jpg',
    youtubeId: 'eY12pdcf3Fw',
  },
  {
    id: 'v5',
    title: 'Rap10: Substituições SEM GLÚTEN',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/pdf3z1e4-aA/mqdefault.jpg',
    youtubeId: 'pdf3z1e4-aA',
  },
  {
    id: 'v6',
    title: 'Panquecas SEM GLÚTEN perfeitas para você',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/2RZtYAu0iII/mqdefault.jpg',
    youtubeId: '2RZtYAu0iII',
  },
  {
    id: 'v7',
    title: 'Congelando vegetais: Coma todo dia!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/61MuWqxaqww/mqdefault.jpg',
    youtubeId: '61MuWqxaqww',
  },
  {
    id: 'v8',
    title: 'O pão Low Carb mais fácil do mundo',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/HaLrULPMZo8/mqdefault.jpg',
    youtubeId: 'HaLrULPMZo8',
  },
  {
    id: 'v9',
    title: 'Estoque de Lanches Saudáveis: Dicas',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/8k7wbvlKg3Q/mqdefault.jpg',
    youtubeId: '8k7wbvlKg3Q',
  },
  {
    id: 'v10',
    title: 'Receita de Cookie Saudável!',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/rIa4VwBib24/mqdefault.jpg',
    youtubeId: 'rIa4VwBib24',
  },
  // Grupo 2
  {
    id: 'v11',
    title: 'Ideias de ALMOÇO e SOBREMESA para 2025',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/wA4Lq4anNtk/mqdefault.jpg',
    youtubeId: 'wA4Lq4anNtk',
  },
  {
    id: 'v12',
    title: 'Bolinhos nutritivos de arroz',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/UhLbElipOCs/mqdefault.jpg',
    youtubeId: 'UhLbElipOCs',
  },
  {
    id: 'v13',
    title: 'Almoço rápido, saudável e delicioso!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/05qFYSFA8qk/mqdefault.jpg',
    youtubeId: '05qFYSFA8qk',
  },
  {
    id: 'v14',
    title: '10 Receitas para aliviar a TPM',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/_ql5lSOvA2I/mqdefault.jpg',
    youtubeId: '_ql5lSOvA2I',
  },
  {
    id: 'v15',
    title: 'Organizando frutas para a semana',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/pgB9peTscaY/mqdefault.jpg',
    youtubeId: 'pgB9peTscaY',
  },
  {
    id: 'v16',
    title: 'Organizando carnes para 2 semanas',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/OijOC2L2Grg/mqdefault.jpg',
    youtubeId: 'OijOC2L2Grg',
  },
  {
    id: 'v17',
    title: 'Salgados SEM GLÚTEN incríveis!',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/hqi-4MWndps/mqdefault.jpg',
    youtubeId: 'hqi-4MWndps',
  },
  {
    id: 'v18',
    title: 'Lanche do Mês em apenas 1 HORA!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/jSoYShb4xmE/mqdefault.jpg',
    youtubeId: 'jSoYShb4xmE',
  },
  {
    id: 'v19',
    title: 'Cookies saudáveis e sem glúten',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/UNJIXb3IylY/mqdefault.jpg',
    youtubeId: 'UNJIXb3IylY',
  },
  {
    id: 'v20',
    title: 'Ideias de Marmitas da Semana',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/q09jEYTDXgs/mqdefault.jpg',
    youtubeId: 'q09jEYTDXgs',
  },
  // Grupo 3
  {
    id: 'v21',
    title: '4 receitas incríveis com ABACATE',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/9hJSyxuur5A/mqdefault.jpg',
    youtubeId: '9hJSyxuur5A',
  },
  {
    id: 'v22',
    title: 'Lanches Saudáveis na Airfryer',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/GdTkEeWXAPc/mqdefault.jpg',
    youtubeId: 'GdTkEeWXAPc',
  },
  {
    id: 'v23',
    title: 'Como eu faço estoque de LANCHES?',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/Dzqfz48fj2Q/mqdefault.jpg',
    youtubeId: 'Dzqfz48fj2Q',
  },
  {
    id: 'v24',
    title: 'Molho de Tomate Turbinado',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/a-E7Va6JFt8/mqdefault.jpg',
    youtubeId: 'a-E7Va6JFt8',
  },
  {
    id: 'v25',
    title: '2kg de bolinhos de carne saudáveis!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/hCh2PqpDlsw/mqdefault.jpg',
    youtubeId: 'hCh2PqpDlsw',
  },
  {
    id: 'v26',
    title: 'Lanche rápido com 1 ovo batido',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/stbIoGojBWI/mqdefault.jpg',
    youtubeId: 'stbIoGojBWI',
  },
  {
    id: 'v27',
    title: 'Lancheira especial de Páscoa',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/YQ7oYRpVAzQ/mqdefault.jpg',
    youtubeId: 'YQ7oYRpVAzQ',
  },
  {
    id: 'v28',
    title: 'Muffin RECHEADO com geleia',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/XMvIc0bEkmE/mqdefault.jpg',
    youtubeId: 'XMvIc0bEkmE',
  },
  {
    id: 'v29',
    title: 'Preparando refeições para a semana',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/jQQBd807VrI/mqdefault.jpg',
    youtubeId: 'jQQBd807VrI',
  },
  {
    id: 'v30',
    title: 'Substitua o Pão: 4 alternativas',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/kqd0X-xeky4/mqdefault.jpg',
    youtubeId: 'kqd0X-xeky4',
  },
  // Grupo 4
  {
    id: 'v31',
    title: 'Cookies Proteicos (Sem Glúten)',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/wGIKmbML_EE/mqdefault.jpg',
    youtubeId: 'wGIKmbML_EE',
  },
  {
    id: 'v32',
    title: 'A SOLUÇÃO para o seu LANCHE',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/BQkUNYTt0F0/mqdefault.jpg',
    youtubeId: 'BQkUNYTt0F0',
  },
  {
    id: 'v33',
    title: 'Balinhas de gelatina tipo FINI',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/coK8cEJoMm8/mqdefault.jpg',
    youtubeId: 'coK8cEJoMm8',
  },
  {
    id: 'v34',
    title: 'MUFFIN SALGADO para lancheira',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/HYx23TKsHK0/mqdefault.jpg',
    youtubeId: 'HYx23TKsHK0',
  },
  {
    id: 'v35',
    title: 'Lanche do mês em 1 hora!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/jTwZQzm21cQ/mqdefault.jpg',
    youtubeId: 'jTwZQzm21cQ',
  },
  {
    id: 'v36',
    title: '4 RECEITAS com abóbora cabotiá',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/wTJzwn0Xw6U/mqdefault.jpg',
    youtubeId: 'wTJzwn0Xw6U',
  },
  {
    id: 'v37',
    title: 'Doces sem açúcar: rápidos e fáceis',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/fiK-o7ArvMw/mqdefault.jpg',
    youtubeId: 'fiK-o7ArvMw',
  },
  {
    id: 'v38',
    title: 'Donuts SAUDÁVEIS para fazer',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/m-8hGttP5Po/mqdefault.jpg',
    youtubeId: 'm-8hGttP5Po',
  },
  {
    id: 'v39',
    title: 'A coxinha mais fácil da mundo!',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/BScCF0C7_Do/mqdefault.jpg',
    youtubeId: 'BScCF0C7_Do',
  },
  {
    id: 'v40',
    title: 'Bolinho de chocolate sem glúten',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/WQ5AWLFTvag/mqdefault.jpg',
    youtubeId: 'WQ5AWLFTvag',
  },
  // Grupo 5
  {
    id: 'v41',
    title: 'BISCOITO DE BATATA DOCE E CHIA',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/gkkWAUqPNmU/mqdefault.jpg',
    youtubeId: 'gkkWAUqPNmU',
  },
  {
    id: 'v42',
    title: 'WAFFLE SALGADO SEM GLÚTEN',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/cbQ5atBrqnU/mqdefault.jpg',
    youtubeId: 'cbQ5atBrqnU',
  },
  {
    id: 'v43',
    title: 'COOKIE SEM GLUTEN saudável',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/Lx8CA0wXupc/mqdefault.jpg',
    youtubeId: 'Lx8CA0wXupc',
  },
  {
    id: 'v44',
    title: 'Bolo de chocolate SEM GLÚTEN',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/nqI-lg9TxgE/mqdefault.jpg',
    youtubeId: 'nqI-lg9TxgE',
  },
  {
    id: 'v45',
    title: 'Biscoito CACAU, AMENDOIM e AVEIA',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/GNniaLpirh8/mqdefault.jpg',
    youtubeId: 'GNniaLpirh8',
  },
  {
    id: 'v46',
    title: 'BOLINHO DE MILHO VERDE',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/9S1G1XiOoYY/mqdefault.jpg',
    youtubeId: '9S1G1XiOoYY',
  },
  {
    id: 'v47',
    title: 'ESTOQUE DE LANCHES congeláveis',
    category: 'Salgadas',
    thumbnail: 'https://img.youtube.com/vi/VP-aK8QmT3k/mqdefault.jpg',
    youtubeId: 'VP-aK8QmT3k',
  },
  {
    id: 'v48',
    title: 'TORTINHA SALGADA sem glúten',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/4pLA9pC8MwA/mqdefault.jpg',
    youtubeId: '4pLA9pC8MwA',
  },
  {
    id: 'v49',
    title: 'BOLINHO SEM GLUTEN saudável',
    category: 'Sem Glúten',
    thumbnail: 'https://img.youtube.com/vi/h7B2epL1wOw/mqdefault.jpg',
    youtubeId: 'h7B2epL1wOw',
  },
  {
    id: 'v50',
    title: 'Sorvete de FRUTAS saudável',
    category: 'Doces',
    thumbnail: 'https://img.youtube.com/vi/c1GdBZDTwew/mqdefault.jpg',
    youtubeId: 'c1GdBZDTwew',
  },
];

export const BONUSES: Bonus[] = [
  {
    id: 'b1',
    title: 'Lista de Compras Semanal',
    description: 'Organize sua ida ao mercado e economize tempo.',
    icon: 'ShoppingCart',
    url: 'https://drive.google.com/file/d/1AQyOlk6cX_dMH5ZqJae2frSRdX7kLNiO/view?usp=drive_link',
  },
  {
    id: 'b2',
    title: 'Guia Sem Glúten e Lactose',
    description: 'Adaptações seguras para restrições alimentares.',
    icon: 'ShieldCheck',
    url: 'https://drive.google.com/file/d/1pI-Fj6Coycz3ZLezYwW_JLKcGBi6la44/view?usp=drive_link',
  },
  {
    id: 'b3',
    title: 'Guia Montagem 10 min',
    description: 'Técnicas de "meal prep" para lancheiras.',
    icon: 'Timer',
    url: 'https://drive.google.com/file/d/1n1zlEkBnP6v_-rGWCyuwg-c-FqCxFAAG/view?usp=drive_link',
  },
  {
    id: 'b4',
    title: 'Substituições Inteligentes',
    description: 'Troque ingredientes sem perder o sabor.',
    icon: 'RefreshCw',
  },
  {
    id: 'b5',
    title: 'Guia Anti-desperdício',
    description: 'Aproveite 100% dos alimentos.',
    icon: 'Leaf',
  },
];

export const OFFERS: Offer[] = [
  {
    id: 'o1',
    title: 'Renda Extra com Caseirinhos',
    description: 'Aprenda a fazer até R$3.000 por mês com bolos caseiros. O curso contem aulas das principais receitas e como fazer para ter muitas encomendas através das redes sociais, mesmo sem experiência ou equipamentos.',
    oldPrice: 'R$147',
    newPrice: 'R$29,90',
    image: 'https://i.ibb.co/nqTw4YVY/9.jpg',
    url: 'https://www.ggcheckout.com/checkout/v2/4oghUjvqTuuQW9hZhekN'
  },
  {
    id: 'o2',
    title: '60 Atividades Bíblicas Divertidas para seu filho amar a Palavra de Deus desde cedo',
    description: 'Atividades para colorir, Histórias bíblicas, Roteiro de Versículos, Orações E muito mais.',
    oldPrice: 'R$97',
    newPrice: 'R$19,90',
    image: 'https://i.ibb.co/NnyzcSKk/8.jpg',
    url: 'https://www.ggcheckout.com/checkout/v2/bCLcmv1ydzS70Um3pFLx'
  },
  {
    id: 'o3',
    title: 'Boobie Goods Cristão: centenas de livros de colorir cristãos no famoso estilo boobie goods',
    description: 'A melhor forma de fazer seu filh se familiarizar com a palavra de Deus e eventos bíblicos enquanto se diverte.',
    oldPrice: 'R$47',
    newPrice: 'R$9,90',
    image: 'https://i.ibb.co/5Xtsv531/7.jpg',
    url: 'https://www.ggcheckout.com/checkout/v2/KdBq8k7nrtjMrGoL6nle'
  }
];
